-- SUPERSEDED. The database schema now lives in supabase/migrations/ (applied to the
-- live Supabase project on 2026-10-05). Do not run the old draft of this file: it
-- conflicts with the applied tables. Phase 4 adds the `moods` and
-- `store_recommendations` tables as a new migration.
